    $(".btn").on("click", function() {
      $(".input").toggleClass("inclicked");
      $(".btn").toggleClass("close");
    });
 $('#searchanimation').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    dots:false,
    autoplay:true,
    smartSpeed:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:2
        }
    }
   })
});
